service: prisma-aws-lambda-example
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x

functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: handlers/seed.handler
    events:
      - http:
          method: GET
          path: /seed
  login:
    handler: handlers/login.handler
    events:
      - http:
          method: POST
          path: /login
  signUp:
    handler: handlers/signUp.handler
    events:
      - http:
          method: POST
          path: /sign-up
  operations:
    handler: handlers/operations.handler
    events:
      - http:
          method: POST
          path: /operations
  transactions:
    handler: handlers/transactions.handler
    events:
      - http:
          method: POST
          path: /transactions

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
